server:
  port: 8088
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:~/local
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace